apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: ccd-etl-writer
 namespace: ccd-etl
 annotations:
  - aadpodidentity.k8s.io/Behavior: namespaced
spec:
 type: 0
 ResourceID: "/subscriptions/a5453007-c32b-4336-9c79-3f643d817aea/resourcegroups/ccd-etl-v1/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ccd-etl-writer-test1"
 ClientID: 10b0c200-4743-458c-98e9-e3e7ab2e0d81
