---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azmsi-writer
  namespace: ccd-etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azmsi-writer
  template:
    metadata:
      labels:
        app: azmsi-writer
        aadpodidbinding: ccd-etl-writer
    spec:
      containers:
        - image: hmcts/azmsi:latest
          name: azmsi-writer
          env:
            - name: MSI_CLIENT_ID
              value: 10b0c200-4743-458c-98e9-e3e7ab2e0d81
            - name: MSI_BLOB_OPERATION
              value: write
            - name: MSI_BLOB_ACCOUNT
              value: ccdetlacc1
            - name: MSI_BLOB_CONTAINER
              value: bsc1
            - name: MSI_BLOB_FILE
              value: testblob1.txt
            - name: MSI_BLOB_CONTENT
              value: "Blob created by pod authenticated using managed identity."
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          imagePullPolicy: Always
